version: '3'

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - redisdb
    environment:
      - AG_REDIS_HOST=redisdb
      - AG_REDIS_PORT=6379
    ports:
      - "8000:8000"
    networks:
            - frontend
  redisdb:
      image: redis
      ports:
          - "6379"
      volumes:
          - redis_data:/data
      networks:
            - frontend

networks:
    frontend:
volumes:
    redis_data:
